pipeline {
  agent any
  environment {
    REGISTRY = '192.168.1.19:5000/task14'
    IMAGE_TAG = "${env.GIT_COMMIT.take(7)}"
  }
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }
    stage('Build & Push') {
      steps {
        script {
          docker.build("${REGISTRY}:${IMAGE_TAG}", "/home/ubuntu/DevOps_Kit/Docker/task14")
          docker.push("${REGISTRY}:${IMAGE_TAG}")
        }
      }
    }
    stage('Deploy') {
      steps {
        sh """
          docker stop web || true
          docker rm web || true
          docker run -d --name web -p 80:80 ${REGISTRY}:${IMAGE_TAG}
        """
      }
    }
  }
  post {
    always { cleanWs() }
  }
}
