---
- name: Подготовка серверов
  hosts: all
  become: yes
  roles:
    - common

- name: Установка докер
  hosts: all
  become: yes
  roles:
    - docker

- name: деплойк контейнеров
  hosts: all
  become: yes
  roles:
    - deploy
