---
# убунту
- name: Install Docker (Ubuntu)
  block:
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

  when: ansible_os_family == "Debian"

# амазон линукс
- name: Install Docker (Amazon Linux)
  block:
    - name: Install Docker via yum
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

  when: ansible_os_family == "RedHat"

# Установка Docker Compose для всех ОС
- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'  # пермишены на выполнения
