---
# питон для Amazon Linux
- name: Install Python (Amazon Linux)
  raw: sudo yum install -y python3
  when: ansible_os_family == "RedHat"

# Питон для убунты
- name: Install Python (Ubuntu)
  raw: sudo apt update && sudo apt install -y python3
  when: ansible_os_family == "Debian"

# Установка Git и Curl
- name: Install git and curl
  package:
    name: "{{ ['git', 'curl'] if ansible_os_family == 'Debian' else 'git' }}"
    state: present
