groups:
- name: instance-cpu
  rules:
  - alert: HighCPUInstance1
    expr: (100 - (avg(irate(node_cpu_seconds_total{mode="idle", instance="instance1"}[1m])) * 100 > 70
    for: 1m
    labels:
      severity: critical
    annotations:
      description: "Загрузка цпу на первом инстансе: {{ $value | printf \"%.2f\" }}%"

- name: instance-memory
  rules:
  - alert: HighMemoryInstance2
    expr: (1 - (node_memory_MemAvailable_bytes{instance="instance2"} / node_memory_MemTotal_bytes{instance="instance2"})) * 100 > 80
    for: 1m
    labels:
      severity: warning
    annotations:
      description: "Памяти использовано на втором инстансе: {{ $value | printf \"%.2f\" }}%"
