groups:
- name: instance-alerts
  rules:
  - alert: HighCpuInstance1
    expr: (100 - (avg(irate(node_cpu_seconds_total{instance="instance1", mode="idle"}[1m]))) * 100) > 70
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "CPU overload ({{ $value | printf \"%.2f\" }}%)"
      description: "Загрузка CPU на instance1 превысила 80%"

  - alert: HighRamInstance2
    expr: (node_memory_MemAvailable_bytes{instance="instance2"} / node_memory_MemTotal_bytes) * 100 < 20
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Low RAM ({{ $value | printf \"%.2f\" }}%)"
      description: "На instance2 осталось меньше 20% свободной RAM"
