global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'instance1-cpu'
    static_configs:
      - targets: ['35.170.248.165:9100']
        labels:
          instance: "instance1"
          metric_type: "cpu"

  - job_name: 'instance2-ram'
    static_configs:
      - targets: ['3.85.9.154:9100']
        labels:
          instance: "instance2"
          metric_type: "ram"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
