version: '3'

services:
  nginx:
    image: nginx:stable-alpine3.20
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
    networks:
      - loki-network

  loki:
    image: grafana/loki:main-8a17983
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki-network

  promtail:
    image: grafana/promtail:main-4cb0fc8
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - ./nginx/logs:/var/log/nginx
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki-network

  grafana:
    image: grafana/grafana:11.6.0-ubuntu
    ports:
      - "3000:3000"
    networks:
      - loki-network

networks:
  loki-network:
