version: '3.8'
services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - flask-net

  web:
    build: .
    image: mikitadziubko/repolesta:latest
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - flask-net
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done;
      python create_tables.py &&
      flask run --host=0.0.0.0 --port=5000"

networks:
  flask-net:
    driver: bridge

volumes:
  postgres_data:
