pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'mikitadziubko/repolesta'
        DOCKER_TAG = 'latest'
        DEPLOY_HOST = 'ubuntu@37.9.53.167'
        DEPLOY_PATH = '/home/ubuntu/app'
    }

    stages {
        stage('Build') {
            steps {
                dir('flask-api') {
                    sh '''
                    docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
                    '''
                }
            }
        }

        stage('Lint') {
            steps {
                dir('flask-api') {
                    sh '''
                    docker run --rm \
                        -v "$PWD":/app \
                        -w /app \
                        python:3.10-slim \
                        /bin/bash -c "pip install flake8 && flake8 ."
                    '''
                }
            }
        }

        stage('Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    dir('flask-api') {
                        sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
                        '''
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                sshagent(['ssh-credentials']) {
                    dir('flask-api') {
                        withCredentials([file(credentialsId: 'env-file-id', variable: 'ENV_FILE')]) {
                            sh """
			    rm -f .env
                            cp \$ENV_FILE .env
                            scp docker-compose.yml .env ${DEPLOY_HOST}:${DEPLOY_PATH}/
                            ssh ${DEPLOY_HOST} "cd ${DEPLOY_PATH} && docker-compose down && docker-compose pull && docker-compose up -d"
                            """
                        }
                    }
                }
            }
        }
    }
}

