pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'mikitadziubko/repolesta'
        DOCKER_TAG = 'latest'
        DEPLOY_HOST = 'user@your-server.com'
        DEPLOY_PATH = '/home/user/app'
    }

    stages {
        stage('Build') {
            steps {
                dir('flask-api') {
                    sh 'docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .'
                }
            }
        }

        stage('Lint') {
            steps {
                dir('flask-api') {
                    sh '''
                    # Установка pip3, если он не установлен
                    if ! command -v pip3 >/dev/null 2>&1; then
                      echo "pip3 not found. Installing..."
                      sudo apt-get update && sudo apt-get install -y python3-pip
                    fi

                    # Установка flake8
                    pip3 install --user flake8

                    # Добавим ~/.local/bin в PATH
                    export PATH=$HOME/.local/bin:$PATH

                    # Запуск flake8
                    flake8 .
                    '''
                }
            }
        }

        stage('Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    dir('flask-api') {
                        sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
                        '''
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                sshagent(['ssh-credentials']) {
                    dir('flask-api') {
                        sh """
                        scp docker-compose.yml .env ${DEPLOY_HOST}:${DEPLOY_PATH}/
                        ssh ${DEPLOY_HOST} "cd ${DEPLOY_PATH} && docker-compose down && docker-compose pull && docker-compose up -d"
                        """
                    }
                }
            }
        }
    }
}

