version: '3'

services:
  prometheus:
    image: prom/prometheus:v3.3.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - monitor-net

  node-exporter:
    image: prom/node-exporter:v1.9.1
    ports:
      - 9100:9100
    networks:
      - monitor-net

  loki:
    image: grafana/loki:main-8a17983
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    networks:
      - monitor-net

  promtail:
    image: grafana/promtail:main-4cb0fc8
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:11.6.0-ubuntu
    depends_on:
      - prometheus
      - loki
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    networks:
      - monitor-net

networks:
  monitor-net:
