---
- name: Клонирование репозитория
  git:
    repo: "https://github.com/picard2104/DevOps_Kit.git"
    dest: /opt/app
    version: main
    force: yes
    update: yes
    recursive: yes

- name: Создание целевой директории
  file:
    path: /opt/docker-app
    state: directory
    mode: '0755'

- name: Копирование файлов проекта
  synchronize:
    src: "/home/ubuntu/DevOps_Kit/Docker/task14/"
    dest: "/opt/docker-app/"
    mode: push
    delete: yes
    rsync_opts:
      - --exclude=.git

- name: Проверка наличия docker-compose.yml
  stat:
    path: /opt/docker-app/docker-compose.yml
  register: compose_file

- name: Проверка существования docker-compose
  fail:
    msg: "Файл docker-compose.yml не найден!"
  when: not compose_file.stat.exists

- name: Запуск контейнеров
  command: docker-compose up -d
  args:
    chdir: /opt/docker-app
