---
- name: клонирование гитхаб репозитория
  git:
    repo: "https://github.com/picard2104/DevOps_Kit.git"
    dest: /opt/app
    version: main
    sparse_paths: "Docker/task14"

- name: копирование файлов проекта
  synchronize:
    src: "/opt/app/Docker/task14/"
    dest: "/opt/docker-app"
    delete: yes

- name: Проверка наличия докеркомпоуз файла
  stat:
    path: /opt/docker-app/docker-compose.yml
  register: compose_file

- name: файл докеркомпоуз не найден
  fail:
    msg: "docker-compose.yml что-то пошло не так и файл не найден!"
  when: not compose_file.stat.exists

- name: пошли крутиться контейнеры
  command: docker-compose up -d
  args:
    chdir: /opt/docker-app
