groups:
- name: cpu-alert
  rules:
  - alert: HighCPU
    expr: (100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100)) > 70
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "CPU {{ $value | printf \"%.2f\" }}%! сервер перегружен"
